site_name: "JDG — ИП в Польше"
site_description: "Гайд по регистрации и ведению JDG (ИП) в Польше"
site_url: https://sobolevbel.github.io/jdg/
repo_url: https://github.com/sobolevbel/jdg
repo_name: sobolevbel/jdg

nav:
  - Главная: index.md
  - PESEL: pesel.md
  - Profil Zaufany: pz.md
  - Регистрация:    # section
    - Регистрация JDG: registration_jdg.md
    - Регистрация VAT: registration_vat.md
    - Регистрация VAT-UE: registration_vat_ue.md
  - ZUS:    # section
    - ZUS: zus.md
    - Переход на Składki Preferencyjne и Duży ZUS: zus_obnizone_skladki.md
    - ZUS-Каникулы: zus_vacation.md
  - Налоги: taxes.md
  - Декларации: declarations.md
  - Легализация: legalization.md
  - Рабочий процесс: workflow.md
  - Как отправить письмо в налоговую: pismo_ogolne.md
  - Ежемесячные операции в infakt.pl: infakt_routine.md
  - Словарь: glossary.md
  - F.A.Q.: faq.md
  - Что нового: whatsnew.md
  - ♥&nbsp;Поддержать: support.md

theme:
  name: material
  custom_dir: overrides
  accent: indigo
  features:
    - navigation.top
    - navigation.expand   # expand sections in nav menu
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  edit_uri: edit/master/docs/
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      lang:
      - ru
      - en
  - git-revision-date-localized

markdown_extensions:
  - attr_list     # for Buttons
  - admonition    # for Admonitions, also known as call-outs,
  - pymdownx.details    # for Admonitions, also known as call-outs,
  - pymdownx.superfences    # for Admonitions, also known as call-outs,
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      slugify: !!python/name:slugify.slugify
      permalink: ¶
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  homepage: https://sobolevbel.github.io/jdg/

  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage

copyright: <a href="#__consent">Change cookie settings</a>

extra_css:
  - css/extra.css

extra_javascript:
  - https://www.googletagmanager.com/gtag/js?id=G-65Z83YVGT1
  - javascript/extra.js
