site_name: "JDG â€” Ð˜ÐŸ Ð² ÐŸÐ¾Ð»ÑŒÑˆÐµ"
site_description: "Ð“Ð°Ð¹Ð´ Ð¿Ð¾ Ñ€ÐµÐ³Ð¸ÑÑ‚Ñ€Ð°Ñ†Ð¸Ð¸ Ð¸ Ð²ÐµÐ´ÐµÐ½Ð¸ÑŽ JDG (Ð˜ÐŸ) Ð² ÐŸÐ¾Ð»ÑŒÑˆÐµ"
site_url: https://sobolevbel.github.io/jdg/
repo_url: https://github.com/sobolevbel/jdg
repo_name: sobolevbel/jdg

nav:
  - Ð“Ð»Ð°Ð²Ð½Ð°Ñ: index.md
  - PESEL: pesel.md
  - Profil Zaufany: pz.md
  - Ð ÐµÐ³Ð¸ÑÑ‚Ñ€Ð°Ñ†Ð¸Ñ JDG Ð¸ VAT: registration.md
  - ZUS: zus.md
  - ÐŸÐµÑ€ÐµÑ…Ð¾Ð´ Ð½Ð° ObniÅ¼one skÅ‚adki ZUS: zus_obnizone_skladki.md
  - ÐÐ°Ð»Ð¾Ð³Ð¸: taxes.md
  - Ð”ÐµÐºÐ»Ð°Ñ€Ð°Ñ†Ð¸Ð¸: declarations.md
  - Ð›ÐµÐ³Ð°Ð»Ð¸Ð·Ð°Ñ†Ð¸Ñ: legalization.md
  - Ð Ð°Ð±Ð¾Ñ‡Ð¸Ð¹ Ð¿Ñ€Ð¾Ñ†ÐµÑÑ: workflow.md
  - Ð ÑƒÑ‚Ð¸Ð½Ð½Ñ‹Ðµ Ð¾Ð¿ÐµÑ€Ð°Ñ†Ð¸Ð¸ (Ð½Ð° Ð¿Ñ€Ð¸Ð¼ÐµÑ€Ðµ infakt.pl): infakt_routine.md
  - F.A.Q.: faq.md
  - Ð§Ñ‚Ð¾ Ð½Ð¾Ð²Ð¾Ð³Ð¾: whatsnew.md

theme:
  name: material
  custom_dir: overrides
  accent: indigo
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  edit_uri: edit/master/docs/
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      lang:
      - ru
      - en
  - git-revision-date-localized

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: ðŸ”—

extra:
  homepage: https://sobolevbel.github.io/jdg/
  features:
    - header.autohide

  analytics:
    provider: google
    property: G-65Z83YVGT1

  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage

copyright: >
  Copyright &copy; 2021 - 2022 Yauheni Sobaleu â€“
  <a href="#__consent">Change cookie settings</a>
